name: Docker Image Build and Test

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/docker-build-test.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
  workflow_dispatch: 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: polars-data-analysis:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Test Python imports
        run: |
          docker run --rm polars-data-analysis:test python -c "
          import sys
          import importlib
          
          required_packages = [
            'numpy', 'pandas', 'matplotlib', 'seaborn', 
            'sklearn', 'polars', 'jupyter'
          ]
          
          failed_imports = []
          for package in required_packages:
              try:
                  importlib.import_module(package)
                  print(f'✓ {package} imported successfully')
              except ImportError as e:
                  failed_imports.append(f'{package}: {str(e)}')
          
          if failed_imports:
              print('The following packages failed to import:')
              for failure in failed_imports:
                  print(f'  ✗ {failure}')
              sys.exit(1)
          else:
              print('All imports successful!')
          "
      
      - name: Test Jupyter functionality
        run: |
          docker run --rm polars-data-analysis:test bash -c "
          jupyter --version && 
          echo 'print(\"Hello from Jupyter\")' > test.py && 
          jupyter nbconvert --to notebook --execute test.py
          "

